### ISSUE TITLE
[Idea] Allow configuration of pattern groups through a config file

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/kubectl-allctx#6]
What if there was a file that holds common queries, in a rc file somewhere on the home dir:

e.g.
```
context-groups:
  prod-new:
    include: "/prod/"
    exclude: "^/legacy/"
  stg:
    include: "/stg/"
```
```
$ kubectl allctx -g prod -- get nodes # g used as a flag for context group 
```
